# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqxU9LrR69h8LJYQWU5xDAw3TvTmh64N
"""

import random
#declaration
fixed_number=7

#begin_code
number=int(input("digite o número secreto  "))
while fixed_number != random.randint(1,10):
  print("ERRADO OTÁRIO")
  number=int(input("digite dnv "))

print("ACERTOU! MISERAVEL")

#end_code

