# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqxU9LrR69h8LJYQWU5xDAw3TvTmh64N
"""

#declaration
note=0

#begin_code

for i in range(3):
  note=int(input("digite suas notas "))+note

result=note/3

if result >= 7:
  print("voce passou")
  print("sua média é ",result)
else:
  print("voce perdeu")
  print("sua média é ",result)

#end_code